// DO NOT EDIT THIS FILE! IT IS AUTOMATICALLY GENERATED FROM FILE "src/ParserRobot202310.gold"
import gold.*;
import gold.structures.*;
import gold.structures.automaton.*;
import gold.structures.bag.*;
import gold.structures.collection.*;
import gold.structures.deque.*;
import gold.structures.disjointset.*;
import gold.structures.graph.*;
import gold.structures.heap.*;
import gold.structures.list.*;
import gold.structures.map.*;
import gold.structures.multimap.*;
import gold.structures.point.*;
import gold.structures.queue.*;
import gold.structures.set.*;
import gold.structures.stack.*;
import gold.structures.tree.*;
import gold.structures.tree.binary.*;
import gold.structures.tree.nary.*;
import gold.structures.tuple.*;
import gold.structures.turingMachine.*;
import gold.swing.*;
import gold.swing.icon.*;
import gold.swing.icon.ajaxload.*;
import gold.swing.icon.famfamfam.*;
import gold.swing.icon.gold.*;
import gold.swing.icon.jlfgr.*;
import gold.swing.icon.wikimedia.*;
import gold.swing.icon.windows.*;
import gold.swing.look.*;
import gold.swing.util.*;
import gold.test.*;
import gold.test.automaton.*;
import gold.test.general.*;
import gold.test.graph.*;
import gold.util.*;
import gold.visualization.*;
import gold.visualization.automaton.*;
import gold.visualization.graph.*;
import gold.visualization.quadtree.*;
import gold.visualization.turingMachine.*;
import gold.visualization.util.*;
import java.lang.*;
import org.apfloat.*;
import static gold.util.GReflection.*;
@SuppressWarnings("all")
public final class ParserRobot202310 {
  public static Object toSet(Object C) {
    int $line=0;
    Object $result=null;
    $try:try {
      gold.structures.set.ISet $v1=$newSet();
      $v2:for (Object x:GCollections.unmodifiableCollection(C)) {
        $v1.add(x);
      }
      $result=$v1;
      if (true) break $try;
      $line=3;
      $rethrow(new RuntimeException("The function \"toSet(C:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,ParserRobot202310.class,"toSet",$line);
    }
    return $result;
  }
  public static IPushdownAutomaton createParser(Object A) {
    int $line=0;
    Object $result=null;
    $try:try {
      $line=8;
      Object Q=$fix($opIntvlY(0,17));
      $line=9;
      Object \u03A3=$fix($opUnionY(ParserRobot202310.toSet(A),GCollections.asSet(' ','\n')));
      $line=10;
      Object \u0393=$fix(GCollections.asSet('1'));
      $line=11;
      Object q_0=$fix(0);
      $line=12;
      Object F=$fix(GCollections.asSet(11,13,14,16));
      $line=13;
      Object M=$fix($invokeConstructor(GPushdownAutomaton.class,new Object[]{Q,\u03A3,\u0393,q_0,F}));
      $line=14;
      Object SkipChars=$fix(GCollections.asSet(' ','\n'));
      $line=18;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(0,1,$cast(java.lang.String.class,"R")),new Object[]{});
      $line=20;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(1,2,$cast(java.lang.String.class,"Vv")),new Object[]{});
      $line=21;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(2,3,$cast(java.lang.String.class,",")),new Object[]{});
      $line=22;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(3,3,$cast(java.lang.String.class,"v,")),new Object[]{});
      $line=23;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(3,2,$cast(java.lang.String.class,"v")),new Object[]{});
      $line=25;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(2,4,$cast(java.lang.String.class,"P")),new Object[]{});
      $line=26;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(2,10,$cast(java.lang.String.class,"[")),new Object[]{});
      $line=28;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(1,4,$cast(java.lang.String.class,"P")),new Object[]{});
      $line=29;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(4,5,$cast(java.lang.String.class,"v[|")),new Object[]{});
      $line=31;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(5,6,$cast(java.lang.String.class,"v")),new Object[]{});
      $line=32;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(6,8,$cast(java.lang.String.class,"|")),new Object[]{});
      $line=33;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(6,7,$cast(java.lang.String.class,",")),new Object[]{});
      $line=34;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(7,7,$cast(java.lang.String.class,"v,")),new Object[]{});
      $line=35;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(7,5,$cast(java.lang.String.class,"v")),new Object[]{});
      $line=37;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(5,8,$cast(java.lang.String.class,"|")),new Object[]{});
      $line=38;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(8,9,$cast(java.lang.String.class,"]")),new Object[]{});
      $line=39;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(9,10,$cast(java.lang.String.class,"[")),new Object[]{});
      $line=41;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(1,10,$cast(java.lang.String.class,"[")),new Object[]{});
      $line=42;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(10,11,$cast(java.lang.String.class,"]")),new Object[]{});
      $line=46;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(12,13,$cast(java.lang.String.class,"a:#,v")),new Object[]{});
      $line=48;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(12,13,$cast(java.lang.String.class,"g:v,v")),new Object[]{});
      $line=49;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(12,13,$cast(java.lang.String.class,"g:#,v")),new Object[]{});
      $line=50;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(12,13,$cast(java.lang.String.class,"g:v,#")),new Object[]{});
      $line=51;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(12,13,$cast(java.lang.String.class,"g:#,#")),new Object[]{});
      $line=53;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(12,13,$cast(java.lang.String.class,"m:#")),new Object[]{});
      $line=54;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(12,13,$cast(java.lang.String.class,"m:v")),new Object[]{});
      $line=56;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(12,13,$cast(java.lang.String.class,"t:L")),new Object[]{});
      $line=57;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(12,13,$cast(java.lang.String.class,"t:U")),new Object[]{});
      $line=59;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(12,13,$cast(java.lang.String.class,"f:O")),new Object[]{});
      $line=61;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(12,13,$cast(java.lang.String.class,"p:#,X")),new Object[]{});
      $line=62;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(12,13,$cast(java.lang.String.class,"p:v,X")),new Object[]{});
      $line=64;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(12,13,$cast(java.lang.String.class,"o:#,L")),new Object[]{});
      $line=65;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(12,13,$cast(java.lang.String.class,"o:#,c")),new Object[]{});
      $line=66;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(12,13,$cast(java.lang.String.class,"o:v,L")),new Object[]{});
      $line=67;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(12,13,$cast(java.lang.String.class,"o:v,c")),new Object[]{});
      $line=69;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(12,13,$cast(java.lang.String.class,"i:#,O")),new Object[]{});
      $line=70;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(12,13,$cast(java.lang.String.class,"i:v,O")),new Object[]{});
      $line=72;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(12,13,$cast(java.lang.String.class,"n:")),new Object[]{});
      $line=74;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(13,12,$cast(java.lang.String.class,';')),new Object[]{});
      $line=78;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(12,14,$cast(java.lang.String.class,"v:")),new Object[]{});
      $line=79;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(14,15,$cast(java.lang.String.class,"#")),new Object[]{});
      $line=80;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(14,15,$cast(java.lang.String.class,"v")),new Object[]{});
      $line=81;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(15,12,$cast(java.lang.String.class,';')),new Object[]{});
      $line=83;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(15,16,$cast(java.lang.String.class,",")),new Object[]{});
      $line=84;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(16,16,$cast(java.lang.String.class,"v,")),new Object[]{});
      $line=85;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(16,16,$cast(java.lang.String.class,"#,")),new Object[]{});
      $line=87;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(16,14,$cast(java.lang.String.class,"v")),new Object[]{});
      $line=88;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(16,14,$cast(java.lang.String.class,"#")),new Object[]{});
      $line=89;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(14,12,$cast(java.lang.String.class,';')),new Object[]{});
      $line=93;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(15,16,$cast(java.lang.String.class,"c:O")),new Object[]{});
      $line=95;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(15,16,$cast(java.lang.String.class,"u:#,X")),new Object[]{});
      $line=96;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(15,16,$cast(java.lang.String.class,"u:v,X")),new Object[]{});
      $line=98;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(15,16,$cast(java.lang.String.class,"r:#,O")),new Object[]{});
      $line=99;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(15,16,$cast(java.lang.String.class,"r:v,O")),new Object[]{});
      $line=101;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(15,16,$cast(java.lang.String.class,"h:#,L")),new Object[]{});
      $line=102;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(15,16,$cast(java.lang.String.class,"h:#,c")),new Object[]{});
      $line=103;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(15,16,$cast(java.lang.String.class,"h:v,L")),new Object[]{});
      $line=104;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(15,16,$cast(java.lang.String.class,"h:v,c")),new Object[]{});
      $line=106;
      $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(15,15,$cast(java.lang.String.class,"!:")),new Object[]{});
      $line=113;
      for (Object $v3:GCollections.unmodifiableCollection(Q)) {
        Object q=$v3;
        $line=114;
        for (Object $v4:GCollections.unmodifiableCollection(SkipChars)) {
          Object s=$v4;
          $line=115;
          $invokeMethod("ignore",((gold.structures.automaton.GPushdownAutomaton)M).delta(q,q,$cast(java.lang.String.class,$opAdditY("",s))),new Object[]{});
        }
      }
      $line=119;
      $result=M;
      if (true) break $try;
      $line=120;
      $rethrow(new RuntimeException("The function \"createParser(A:Object)\" did not return a value."));
    }
    catch (Throwable $throwable) {
      $rethrow($throwable,ParserRobot202310.class,"createParser",$line);
    }
    return $cast(IPushdownAutomaton.class,$result);
  }
}
